---
title: "plots_soil_biology"
author: "Joe Collins"
date: "`r Sys.Date()`"
output: pdf_document
---

#___________________________________________
# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rstudioapi::getActiveProject())

# PACKAGES ####

library(dplyr)
library(purrr) # For list filtering
library(stringr) # replace characters
library(ggplot2) # plotting 
library(tidyr)
library(ggpubr)
library(readxl)
```


#___________________________________________
# Data

```{r cars}


dat <- read_excel(path = "sym_link_soil_biology/Data/", sheet = 1)

# remove NA's
dat[is.na(dat)] <- 0

dat$Year <- as.factor(dat$Year)
dat$Treatment <- as.factor(dat$Treatment)
dat$Block <- as.factor(dat$Block)


dat$Treatment <- factor(dat$Treatment, 
                           levels = c("Baseline", "Conservation","Conventional"))


```



#___________________________________________
# Plots



```{r pressure, echo=FALSE}

# Calculates mean, sd, se and IC - block
summ <- dat %>%
  group_by(Treatment, Year) %>%
  summarise( 
    n=n(),
    mean = mean(Phosphorus_mg_l),
    sd = sd(Phosphorus_mg_l)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))

p1 <-   ggplot(data = summ, 
           aes(x = Treatment, 
               y = mean, 
               fill = Treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,25) +
      labs(
        x = element_blank(),
        y = expression(Phosphorus~(Mg~l^{-1})),
        subtitle = expression(Phosphorus~(Mg~l^{-1})), 
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("white","turquoise3","tomato2"), 
                        name = "Treatment") +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            axis.text.x = element_blank()) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~ Year, 
                 ncol = 4, 
                 scales = 'free_x') 


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
